// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Kruise
//
//  Kubernetes service configuration service
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/plain
//
// swagger:meta
package restapi
