// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/ichilly/Kruise/models"
)

// NewCreateAppConfigParams creates a new CreateAppConfigParams object
// no default values defined in spec.
func NewCreateAppConfigParams() CreateAppConfigParams {

	return CreateAppConfigParams{}
}

// CreateAppConfigParams contains all the bound params for the create app config operation
// typically these are obtained from a http.Request
//
// swagger:parameters createAppConfig
type CreateAppConfigParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the application object
	  Required: true
	  In: body
	*/
	Application *models.Application
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateAppConfigParams() beforehand.
func (o *CreateAppConfigParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Application
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("application", "body"))
			} else {
				res = append(res, errors.NewParseError("application", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Application = &body
			}
		}
	} else {
		res = append(res, errors.Required("application", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
