apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.App.Metadata.App}}-docs-ingress
  namespace: {{.App.Metadata.Namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - secretName: tls-secret
  rules:
    - http:
        paths:
          - path: /{{.App.Metadata.App}}/docs(/|$)(.*)
            backend:
              serviceName: {{.App.Metadata.App}}
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.App.Metadata.App}}-api-ingress
  namespace: {{.App.Metadata.Namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - secretName: tls-secret
  rules:
    - http:
        paths:
          - path: /{{.App.Metadata.App}}/apis(/|$)(.*)
            backend:
              serviceName: {{.App.Metadata.App}}
              servicePort: 80
