// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Dependencies dependencies
// swagger:model dependencies
type Dependencies struct {

	// aws
	Aws *bool `json:"aws,omitempty"`

	// mysql
	Mysql *bool `json:"mysql,omitempty"`
}

func (m *Dependencies) UnmarshalJSON(b []byte) error {
	type DependenciesAlias Dependencies
	var t DependenciesAlias
	if err := json.Unmarshal([]byte("{\"aws\":false,\"mysql\":false}"), &t); err != nil {
		return err
	}
	if err := json.Unmarshal(b, &t); err != nil {
		return err
	}
	*m = Dependencies(t)
	return nil
}

// Validate validates this dependencies
func (m *Dependencies) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Dependencies) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Dependencies) UnmarshalBinary(b []byte) error {
	var res Dependencies
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
